// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sampleServer.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GrpcDefinition {

  /// <summary>Holder for reflection information generated from sampleServer.proto</summary>
  public static partial class SampleServerReflection {

    #region Descriptor
    /// <summary>File descriptor for sampleServer.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SampleServerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJzYW1wbGVTZXJ2ZXIucHJvdG8aFHNhbXBsZU1lc3NhZ2VzLnByb3RvMj8K",
            "EFNhbHV0YXRpb25TZXJ2ZXISKwoGU2FsdXRlEg4uU2FtcGxlUmVxdWVzdBoP",
            "LlNhbXBsZVJlc3BvbnNlIgBCEaoCDkdycGNEZWZpbml0aW9uYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SampleMessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
