// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sampleServer.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace GrpcDefinition {
  public static partial class SalutationServer
  {
    static readonly string __ServiceName = "SalutationServer";

    static readonly grpc::Marshaller<global::GrpcDefinition.SampleRequest> __Marshaller_SampleRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcDefinition.SampleRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcDefinition.SampleResponse> __Marshaller_SampleResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcDefinition.SampleResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::GrpcDefinition.SampleRequest, global::GrpcDefinition.SampleResponse> __Method_Salute = new grpc::Method<global::GrpcDefinition.SampleRequest, global::GrpcDefinition.SampleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Salute",
        __Marshaller_SampleRequest,
        __Marshaller_SampleResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcDefinition.SampleServerReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SalutationServer</summary>
    public abstract partial class SalutationServerBase
    {
      public virtual global::System.Threading.Tasks.Task<global::GrpcDefinition.SampleResponse> Salute(global::GrpcDefinition.SampleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SalutationServer</summary>
    public partial class SalutationServerClient : grpc::ClientBase<SalutationServerClient>
    {
      /// <summary>Creates a new client for SalutationServer</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SalutationServerClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SalutationServer that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SalutationServerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SalutationServerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SalutationServerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::GrpcDefinition.SampleResponse Salute(global::GrpcDefinition.SampleRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Salute(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GrpcDefinition.SampleResponse Salute(global::GrpcDefinition.SampleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Salute, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcDefinition.SampleResponse> SaluteAsync(global::GrpcDefinition.SampleRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SaluteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcDefinition.SampleResponse> SaluteAsync(global::GrpcDefinition.SampleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Salute, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SalutationServerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SalutationServerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SalutationServerBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Salute, serviceImpl.Salute).Build();
    }

  }
}
#endregion
