// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sampleMessages.proto

/*
Package sampleMessages is a generated protocol buffer package.

It is generated from these files:
	sampleMessages.proto

It has these top-level messages:
	SampleResponse
	SampleRequest
*/
package sampleMessages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SampleResponse struct {
	Salutation string `protobuf:"bytes,1,opt,name=salutation" json:"salutation,omitempty"`
}

func (m *SampleResponse) Reset()                    { *m = SampleResponse{} }
func (m *SampleResponse) String() string            { return proto.CompactTextString(m) }
func (*SampleResponse) ProtoMessage()               {}
func (*SampleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SampleResponse) GetSalutation() string {
	if m != nil {
		return m.Salutation
	}
	return ""
}

type SampleRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *SampleRequest) Reset()                    { *m = SampleRequest{} }
func (m *SampleRequest) String() string            { return proto.CompactTextString(m) }
func (*SampleRequest) ProtoMessage()               {}
func (*SampleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SampleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*SampleResponse)(nil), "SampleResponse")
	proto.RegisterType((*SampleRequest)(nil), "SampleRequest")
}

func init() { proto.RegisterFile("sampleMessages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x4e, 0xcc, 0x2d,
	0xc8, 0x49, 0xf5, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x57, 0x32, 0xe0, 0xe2, 0x0b, 0x06, 0x8b, 0x07, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a,
	0xc9, 0x71, 0x71, 0x15, 0x27, 0xe6, 0x94, 0x96, 0x24, 0x96, 0x64, 0xe6, 0xe7, 0x49, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x06, 0x21, 0x89, 0x28, 0x29, 0x73, 0xf1, 0xc2, 0x74, 0x14, 0x96, 0xa6, 0x16,
	0x97, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x42, 0x95, 0x82, 0xd9, 0x49, 0x6c, 0x60,
	0xd3, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf6, 0xbb, 0x53, 0xae, 0x75, 0x00, 0x00, 0x00,
}
