# This is a basic workflow to help you get started with Actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build dotnet project
        run: dotnet build

  build_go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: build
      working-directory: ./GoClient
      run: |
      ls
      echo get 1
      go get -u "github.com/tstanitz/GRPC_MultiLanguage/GrpcDefinition"
      echo get 2
      go get -u "google.golang.org/grpc"
      echo build
      go build main.go
      echo done
